name: PullRequestValidation
on: [pull_request]

jobs:
  build:
    name: Module imports on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Perform the import
      shell: pwsh
      run: 
        $ModuleName = 'Smtp4Dev4BcContainers'
        $ModulPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath $ModuleName
        Import-Module $ModulPath -Force -ErrorAction Stop
